### ISSUE TITLE
ffmpeg error - anaconda python 3.8 - 

### ISSUE THREAD

**Issue by rikabi89** [Zz-ww/SadTalker-Video-Lip-Sync#17]
`(SadTalker-Wav2lip) H:\SadTalker-Video-Lip-Sync>
(SadTalker-Wav2lip) H:\SadTalker-Video-Lip-Sync>python inference.py --driven_audio 1.wav --source_video 1.mp4 --use_DAIN
./checkpoints\epoch_20.pth
./checkpoints\auido2pose_00140-model.pth
./checkpoints\auido2exp_00300-model.pth
./checkpoints\facevid2vid_00189-model.pth.tar
./checkpoints\mapping_00109-model.pth.tar
3DMM Extraction for source image
landmark Det:: 100%|███████████████████████████████████████████████████████████████████████████████| 1020/1020 [01:11<00:00, 14.18it/s]
3DMM Extraction In Video:: 100%|███████████████████████████████████████████████████████████████████| 1020/1020 [00:16<00:00, 63.24it/s]
mel:: 100%|███████████████████████████████████████████████████████████████████████████████████████| 423/423 [00:00<00:00, 40052.16it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 124.36it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████████████████████| 423/423 [00:35<00:00, 11.85it/s]
Traceback (most recent call last):
  File "inference.py", line 123, in <module>
    main(args)
  File "inference.py", line 76, in main
    tmp_path, new_audio_path, return_path = animate_from_coeff.generate(data, save_dir, pic_path, crop_info,
  File "H:\SadTalker-Video-Lip-Sync\src\facerender\animate.py", line 154, in generate
    sound = AudioSegment.from_mp3(audio_path)
  File "H:\anaconda3\envs\SadTalker-Wav2lip\lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "H:\anaconda3\envs\SadTalker-Wav2lip\lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 2022-07-06-git-03d81a044a-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 27.100 / 57. 27.100
  libavcodec     59. 36.100 / 59. 36.100
  libavformat    59. 26.100 / 59. 26.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 41.100 /  8. 41.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[mp3float @ 000001c4461b57c0] Header missing
    Last message repeated 127 times
[mp3 @ 000001c44619f200] Could not find codec parameters for stream 0 (Audio: mp3 (mp3float), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mp3, from '1.wav':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: mp3, 0 channels, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s32le (native))
Press [q] to stop, [?] for help
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3float @ 000001c446629b80] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[abuffer @ 000001c4461a1440] Value inf for parameter 'time_base' out of range [0 - 2.14748e+09]
    Last message repeated 1 times
[abuffer @ 000001c4461a1440] Error setting option time_base to value 1/0.
[graph_0_in_0_0 @ 000001c446625e40] Error applying options to the filter.
Error reinitializing filters!
Error while filtering: Result too large
Finishing stream 0:0 without any data written to it.
[abuffer @ 000001c4461da2c0] Value inf for parameter 'time_base' out of range [0 - 2.14748e+09]
    Last message repeated 1 times
[abuffer @ 000001c4461da2c0] Error setting option time_base to value 1/0.
[graph_0_in_0_0 @ 000001c4461da1c0] Error applying options to the filter.
Error configuring filter graph
Conversion failed!`

Not sure what else to do. I've tried different files, uninstall and re-install ffpeg but I keep this, any ideas?

**Comment by rikabi89** [comment]
The issue was related to the .wav file being corrupted or recognized as a .mp3 using a different wav resolved the matter.
