### ISSUE TITLE
Why inferencing are this error? how to resolve it.

### ISSUE THREAD

**Issue by waveboy800** [Zz-ww/SadTalker-Video-Lip-Sync#26]
Traceback (most recent call last):
  File "G:\dev\SadTalker-Video-Lip-Sync-master\inference.py", line 123, in <module>
    main(args)
  File "G:\dev\SadTalker-Video-Lip-Sync-master\inference.py", line 58, in main
    restorer_model = GFPGANer(model_path='checkpoints/GFPGANv1.3.pth', upscale=1, arch='clean',
  File "G:\dev\SadTalker-Video-Lip-Sync-master\third_part\GFPGAN\gfpgan\utils.py", line 76, in __init__
    self.face_helper = FaceRestoreHelper(
  File "E:\anaconda\envs\sadtalker\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 99, in __init__
    self.face_det = init_detection_model(det_model, half=False, device=self.device, model_rootpath=model_rootpath)
  File "E:\anaconda\envs\sadtalker\lib\site-packages\facexlib\detection\__init__.py", line 22, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "E:\anaconda\envs\sadtalker\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\anaconda\envs\sadtalker\lib\site-packages\torch\serialization.py", line 938, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 333577 more bytes. The file might be corrupted.

**Comment by c8241998** [comment]
you should download a complete checkpoint
