### ISSUE TITLE
脸部克隆完成后  总是提示如下错误，cuda和cunnn版本都换了好几次了。还是一样的问题

### ISSUE THREAD

**Issue by menkaiyuan** [Zz-ww/SadTalker-Video-Lip-Sync#33]
W0630 09:16:06.445015 25868 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 10.2
W0630 09:16:06.447014 25868 dynamic_loader.cc:276] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "inference.py", line 123, in <module>
    main(args)
  File "inference.py", line 83, in main
    predictor_dian = dain_predictor.DAINPredictor(args.dian_output, weight_path=args.DAIN_weight,
  File "D:\SadTalker-Video-Lip-Sync\src\dain_model\dain_predictor.py", line 64, in __init__
    self.build_inference_model()
  File "D:\SadTalker-Video-Lip-Sync\src\dain_model\base_predictor.py", line 25, in build_inference_model
    self.program, self.feed_names, self.fetch_targets = paddle.static.load_inference_model(
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\framework.py", line 443, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\static\io.py", line 809, in load_inference_model
    deserialize_persistables(program, params_bytes, executor)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\framework.py", line 443, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\static\io.py", line 650, in deserialize_persistables
    executor.run(load_program)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\executor.py", line 1285, in run
    res = self._run_impl(
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\executor.py", line 1464, in _run_impl
    return new_exe.run(list(feed.keys()), fetch_list, return_numpy)
  File "C:\Users\menka\.conda\envs\stvl\lib\site-packages\paddle\fluid\executor.py", line 547, in run
    tensors = self._new_exe.run(feed_names, fetch_list)._move_to_list()
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:303)

**Comment by menkaiyuan** [comment]
问题已经解决：缺失了cudnn64_7.dll,下载了补上去即可  下在的2019年的v7开头的版本 就有
