### ISSUE TITLE
使用use_DAIN 时报错

### ISSUE THREAD

**Issue by Linkfufu** [Zz-ww/SadTalker-Video-Lip-Sync#35]
The generated video is named ./results\2023_07_10_06.45.09/6##1_full.mp4
Mon Jul 10 06:49:00-WARNING: The old way to load inference model is deprecated. model path: C:\Users\Spencer\PycharmProjects\pythonProject\SadTalker-Video-Lip-Sync\checkpoints\DAIN_weight\model, params path: C:\Users\Spencer\PycharmProjects\pythonProject\SadTalker-Video-Lip-Sync\checkpoints\DAIN_weight\params
W0710 06:49:01.032488  6856 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.2
W0710 06:49:01.032488  6856 gpu_resources.cc:91] device: 0, cuDNN Version: 8.3.
'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Old fps (frame rate):  25.0
New fps (frame rate):  50
[image2 muxer @ 0000000002f30620] Value 0.000000 for parameter 'start_number' out of range [1 - 2.14748e+009]
[image2 muxer @ 0000000002f30620] Error setting option start_number to value 0.
Could not write header for output file #0 (incorrect codec parameters ?): Error number -34 occurred
Traceback (most recent call last):
  File "C:\Users\Spencer\PycharmProjects\pythonProject\SadTalker-Video-Lip-Sync\inference.py", line 123, in <module>
    main(args)
  File "C:\Users\Spencer\PycharmProjects\pythonProject\SadTalker-Video-Lip-Sync\inference.py", line 86, in main
    frames_path, temp_video_path = predictor_dian.run(tmp_path)
  File "C:\Users\Spencer\PycharmProjects\pythonProject\SadTalker-Video-Lip-Sync\src\dain_model\dain_predictor.py", line 97, in run
    out_path = video2frames(video_path, frame_path_input)
  File "C:\Users\Spencer\PycharmProjects\pythonProject\SadTalker-Video-Lip-Sync\src\dain_model\dain_predictor.py", line 36, in video2frames
    raise RuntimeError('ffmpeg process video: {} error'.format(vid_name))
RuntimeError: ffmpeg process video: ead5dc4a-3a48-423d-9996-aab5540abf06 error

**Comment by keepgogoing** [comment]
我也是这个报错
