### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by Pythonpa** [Zz-ww/SadTalker-Video-Lip-Sync#4]
Here is ERROR information when running,是哪里的dll没导入吗？

(sadwav2lip) D:\pythonProject\SadTalker-Video-Lip-Sync>python inference.py --driven_audio sound.wav  --source_video driving.mp4   --enhancer lip
Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    from third_part.GFPGAN.gfpgan import GFPGANer
  File "D:\pythonProject\SadTalker-Video-Lip-Sync\third_part\GFPGAN\gfpgan\__init__.py", line 5, in <module>
    from .archs import *
  File "D:\pythonProject\SadTalker-Video-Lip-Sync\third_part\GFPGAN\gfpgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr\archs\__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr\utils\__init__.py", line 5, in <module>
    from .img_util import crop_border, imfrombytes, img2tensor, imwrite, tensor2img
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr\utils\img_util.py", line 6, in <module>
    from torchvision.utils import make_grid
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\models\__init__.py", line 11, in <module>
    from . import detection
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\ops\boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: DLL load failed: 找不到指定的模块。

**Comment by Zz-ww** [comment]
> Here is ERROR information when running,是哪里的dll没导入吗？
> 
> (sadwav2lip) D:\pythonProject\SadTalker-Video-Lip-Sync>python inference.py --driven_audio sound.wav --source_video driving.mp4 --enhancer lip Traceback (most recent call last): File "inference.py", line 10, in from third_part.GFPGAN.gfpgan import GFPGANer File "D:\pythonProject\SadTalker-Video-Lip-Sync\third_part\GFPGAN\gfpgan__init__.py", line 5, in from .archs import * File "D:\pythonProject\SadTalker-Video-Lip-Sync\third_part\GFPGAN\gfpgan\archs__init__.py", line 2, in from basicsr.utils import scandir File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr__init__.py", line 3, in from .archs import * File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr\archs__init__.py", line 5, in from basicsr.utils import get_root_logger, scandir File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr\utils__init__.py", line 5, in from .img_util import crop_border, imfrombytes, img2tensor, imwrite, tensor2img File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\basicsr\utils\img_util.py", line 6, in from torchvision.utils import make_grid File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision__init__.py", line 1, in from torchvision import models File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\models__init__.py", line 11, in from . import detection File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\models\detection__init__.py", line 1, in from .faster_rcnn import * File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in from torchvision.ops import misc as misc_nn_ops File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\ops__init__.py", line 1, in from .boxes import nms, box_iou File "D:\Anaconda\envs\sadwav2lip\lib\site-packages\torchvision\ops\boxes.py", line 2, in from torchvision import _C ImportError: DLL load failed: 找不到指定的模块。

我这边没在windows上验证

**Comment by Pythonpa** [comment]
是我的问题，我偷懒l了，直接复制原来wav2lip的conda虚拟环境，构建的torch版本比作者的高，导致出问题。按照作者提供的torch和cu版本部署，WIN10，30系显卡8G显存能跑，不过内存需要准备够，32G能吃满。
