### ISSUE TITLE
Inferencing error

### ISSUE THREAD

**Issue by SuperMaximus1984** [Zz-ww/SadTalker-Video-Lip-Sync#41]
Please advise how to avoid this?

```
The generated video is named ./results\2023_07_19_11.11.52/video##audio_full.mp4
Error: Can not import paddle core while this file exists: C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "inference.py", line 123, in <module>
    main(args)
  File "inference.py", line 80, in main
    import paddle
  File "C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\framework\random.py", line 17, in <module>    from paddle import fluid
  File "C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\fluid\core.py", line 356, in <module>
    raise e
  File "C:\Users\Max\anaconda3\envs\SadTalkerLipSync\lib\site-packages\paddle\fluid\core.py", line 269, in <module>
    from . import libpaddle
ImportError: generic_type: type "_gpuDeviceProperties" is already registered!
```

All checkpoints were downloaded correctly and Python 3.8 env installed without any obstacles.

**Comment by shirubei** [comment]
same here with Python 3.10 at windows 11.
Any hints will be appreciated. Thank you!
