### ISSUE TITLE
Hello! I have a problem.

### ISSUE THREAD

**Issue by NeuroDonu** [Zz-ww/SadTalker-Video-Lip-Sync#51]
Traceback (most recent call last):
  File "/content/SadTalker-Video-Lip-Sync/inference.py", line 123, in <module>
    main(args)
  File "/content/SadTalker-Video-Lip-Sync/inference.py", line 47, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/content/SadTalker-Video-Lip-Sync/src/utils/preprocess.py", line 44, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/content/SadTalker-Video-Lip-Sync/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)   
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

I write jupyter notebook for colab and i have this problem. Notebook: https://colab.research.google.com/drive/1zeqfsNl7vZxPUztQzNDT2xRQthaz3Zws

**Comment by diegomagikal** [comment]
Hi! Did you fix this issue? Could you share your solution?

**Comment by Inferencer** [comment]
> AttributeError: _2D

this might help
https://github.com/Zz-ww/SadTalker-Video-Lip-Sync/issues/37

Edit: strange your issue says it's from Sep 16th but was on my recent notifications as posted 27 mins ago

**Comment by NeuroDonu** [comment]
This problem is easily solved, look at my fork, I solved it in it

**Comment by NeuroDonu** [comment]
https://github.com/Zz-ww/SadTalker-Video-Lip-Sync/commit/f147a90f56aae92d0bf23732ad8f8e061897d4c2
